# This file was generated by GoReleaser. DO NOT EDIT.
cask "yeelight-home" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "69206507c3c1d0df15484b0f415c1a9201f2cfaf06c640be52637238cfb11502"
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "d9fd431cb9b2fea1cfc367b30387edae0c36c389a323fa4013204fd629829f6f"
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88dd7a98cd0ee69b367952b0621f81264d843a2b66e889c98ee67b9eb5aba072"
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "48532ecb176554a423c6583cd2fc0d385a55587101cea9075cfacbb2b3d9a5bd"
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-linux-arm64.tar.gz"
    end
  end

  name "yeelight-home"
  desc "Local Yeelight Home Runtime CLI."
  homepage "https://github.com/Yeelight/yeelight-home"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yeelight-home"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yeelight-home"]
    end
  end

  # No zap stanza required

end
