# This file was generated by GoReleaser. DO NOT EDIT.
cask "yeelight-home" do
  version "0.1.26"

  on_macos do
    on_intel do
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-darwin-amd64.tar.gz"
      sha256 "c3ee694095fd51bc1cbdb1947e78e607eae174fe38c8bdf8186f087d102b8336"
    end
    on_arm do
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-darwin-arm64.tar.gz"
      sha256 "14419f30c015754b423ce87e74cf7f9e306f97873790476d0d77d2156f37cb94"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-linux-amd64.tar.gz"
      sha256 "d484cfaf86bc01d8223048f3c79455990c3581ea0b0ae9bd56b6a3b8887132a3"
    end
    on_arm do
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-linux-arm64.tar.gz"
      sha256 "765fefdd393f37154769741c261ca9528b07f3cfe51e0d2b1f8e1fe1f6b7e684"
    end
  end

  name "yeelight-home"
  desc "Local Yeelight Home Runtime CLI."
  homepage "https://github.com/Yeelight/yeelight-home"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yeelight-home"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yeelight-home"]
    end
  end

  # No zap stanza required

end
