# This file was generated by GoReleaser. DO NOT EDIT.
cask "yeelight-home" do
  version "0.1.18"

  on_macos do
    on_intel do
      sha256 "2f28b2f1c8fd8038aed43ca005a4328cda843b00e014b572d6838e92547b3e12"
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "0072d1e624fc1f64a2a8dea745bff7c01d92a023557118e82bb77cf03a55866f"
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "212d2fb152acfa33a162536ae5c5c89e01e810e8bc171c404044f2dab0c87f2c"
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "cb9840e582f58f31805885005dd359d2dd7bd231c29772446a982749a741230d"
      url "https://github.com/Yeelight/yeelight-home/releases/download/v#{version}/yeelight-home-linux-arm64.tar.gz"
    end
  end

  name "yeelight-home"
  desc "Local Yeelight Home Runtime CLI."
  homepage "https://github.com/Yeelight/yeelight-home"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yeelight-home"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yeelight-home"]
    end
  end

  # No zap stanza required

end
