# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YeelightHome < Formula
  desc "Local Yeelight Home Runtime CLI."
  homepage "https://github.com/Yeelight/yeelight-home"
  version "0.1.16"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Yeelight/yeelight-home/releases/download/v0.1.16/yeelight-home-darwin-amd64.tar.gz"
      sha256 "1988a1af7f5b804cedcdcdb2b5552342eef92a09a29c99f0a5e1e00964e301af"

      define_method(:install) do
        bin.install "yeelight-home"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Yeelight/yeelight-home/releases/download/v0.1.16/yeelight-home-darwin-arm64.tar.gz"
      sha256 "ec6e85472bb8a74075906f53eb6c2802f5186afcc619e976cbf668c36858073a"

      define_method(:install) do
        bin.install "yeelight-home"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yeelight/yeelight-home/releases/download/v0.1.16/yeelight-home-linux-amd64.tar.gz"
      sha256 "ce2cc8cc20ae3c15491197541ff9c782d7009f3223107b032ccf3100978e7977"
      define_method(:install) do
        bin.install "yeelight-home"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yeelight/yeelight-home/releases/download/v0.1.16/yeelight-home-linux-arm64.tar.gz"
      sha256 "7b3681bf1bd7f3ed5a6f4e504261e702271332fb51f9abface23ee55042dda6d"
      define_method(:install) do
        bin.install "yeelight-home"
      end
    end
  end

  test do
    assert_match "yeelight-home #{version}", shell_output("#{bin}/yeelight-home version")
  end
end
