# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YeelightHome < Formula
  desc "Local Yeelight Home Runtime CLI."
  homepage "https://github.com/Yeelight/yeelight-home"
  version "0.1.12"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Yeelight/yeelight-home/releases/download/v0.1.12/yeelight-home-darwin-amd64.tar.gz"
      sha256 "449cda63ed569b165e2e611cf9e00332d4a44b59d1170d87792c48d6c6c9ab1c"

      define_method(:install) do
        bin.install "yeelight-home"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Yeelight/yeelight-home/releases/download/v0.1.12/yeelight-home-darwin-arm64.tar.gz"
      sha256 "75528ad571b9960a29b2b35155c714863413cd27baf641a75815db63d0ff3256"

      define_method(:install) do
        bin.install "yeelight-home"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yeelight/yeelight-home/releases/download/v0.1.12/yeelight-home-linux-amd64.tar.gz"
      sha256 "18d77daa47fad9f9b28eeeb401f09edd447dc87522b7ba8be8d7c59c2c80fa92"
      define_method(:install) do
        bin.install "yeelight-home"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yeelight/yeelight-home/releases/download/v0.1.12/yeelight-home-linux-arm64.tar.gz"
      sha256 "1cffdbc507651f980a650e7a8211d5a36c8f81790c46c96ed30a2427c4e2dcd5"
      define_method(:install) do
        bin.install "yeelight-home"
      end
    end
  end

  test do
    assert_match "yeelight-home #{version}", shell_output("#{bin}/yeelight-home version")
  end
end
